// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace StockPredictorML.Model
{
    public class ModelInput
    {
        [ColumnName("Date"), LoadColumn(0)]
        public string Date { get; set; }


        [ColumnName("Open"), LoadColumn(1)]
        public float Open { get; set; }


        [ColumnName("High"), LoadColumn(2)]
        public float High { get; set; }


        [ColumnName("Low"), LoadColumn(3)]
        public float Low { get; set; }


        [ColumnName("Close"), LoadColumn(4)]
        public float Close { get; set; }


        [ColumnName("Volume"), LoadColumn(5)]
        public float Volume { get; set; }


    }
}
